name: IA Apuestas

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: pip install requests pandas openpyxl

      - name: Ejecutar IA
        run: python predicciones.py
